CREATE TABLE SDEV
(SDID INT, 
DevName NVARCHAR(50), 
DEVADDRESS NVARCHAR(50),
PRIMARY KEY (SDID)
);

CREATE TABLE PROJECT
(ProjNum INT, 
TITLE NVARCHAR(50),
DESCRIPT NVARCHAR(50),
PRIMARY KEY (ProjNum),
);

CREATE TABLE ALLOCATION
(SDID INT, 
ProjNum INT,
WeekNum INT, 
PRIMARY KEY (SDID, ProjNum), 
FOREIGN KEY (SDID) REFERENCES SDEV,
FOREIGN KEY (ProjNum) REFERENCES PROJECT, 
FOREIGN KEY (WeekNum) REFERENCES WORKLOG 
);

CREATE TABLE WORKLOG
(SDID INT, 
ProjNum INT, 
WeekNum INT, 
PRIMARY KEY (SDID, ProjNum, WeekNum), 
FOREIGN KEY (SDID) REFERENCES SDEV, 
FOREIGN KEY (ProjNum) REFERENCES PROJECT
);
GO