IF OBJECT_ID('WORKLOG') IS NOT NULL
DROP TABLE WORKLOG;
IF OBJECT_ID('ALLOCATION') IS NOT NULL
DROP TABLE ALLOCATION;
IF OBJECT_ID('SDEV') IS NOT NULL
DROP TABLE SDEV;
IF OBJECT_ID('PROJECT') IS NOT NULL
DROP TABLE PROJECT;
GO


CREATE TABLE SDEV
(SDID NVARCHAR(50), 
DevName NVARCHAR(50), 
DEVADDRESS NVARCHAR(50),
PRIMARY KEY (SDID)
);

CREATE TABLE PROJECT
(ProjNum INT, 
TITLE NVARCHAR(50),
DESCRIPT NVARCHAR(50),
PRIMARY KEY (ProjNum),
);

CREATE TABLE ALLOCATION
(SDID NVARCHAR(50), 
ProjNum INT, 
PRIMARY KEY (SDID, ProjNum), 
FOREIGN KEY (SDID) REFERENCES SDEV,
FOREIGN KEY (ProjNum) REFERENCES PROJECT, 
);

CREATE TABLE WORKLOG
(SDID NVARCHAR(50), 
ProjNum INT, 
WeekNum INT, 
WkHours INT,
PRIMARY KEY (SDID, ProjNum, WeekNum), 
FOREIGN KEY (SDID,ProjNum) REFERENCES ALLOCATION
);


GO

INSERT INTO SDEV (SDID, DevName, DEVADDRESS) VALUES
('SD101', 'Barry Manilow', '10 Wallaby Way, Sydney 3001'),
('SD201', 'Tony Bennet', '50 North St, Bronx, 10000');

INSERT INTO PROJECT (ProjNum, TITLE, DESCRIPT) VALUES
('101', 'Nicuragua', 'Gold Oil and Drugs = freedom for all'),
('102', 'Russia', 'How to deliver a Radioactive Teacup');

INSERT INTO ALLOCATION (SDID, ProjNum) VALUES
('SD101', '101'),
('SD101', '102'),
('SD201', '102');

INSERT INTO WORKLOG (SDID, ProjNum, WeekNum, WkHours) VALUES
('SD101', '101', 5, 30),
('SD101', '102', 4, 8),
('SD201', '102', 6, 38);