IF OBJECT_ID('ALLOCATION') IS NOT NULL
DROP TABLE ALLOCATION;
IF OBJECT_ID('WORKLOG') IS NOT NULL
DROP TABLE WORKLOG;
IF OBJECT_ID('SDEV') IS NOT NULL
DROP TABLE SDEV;
IF OBJECT_ID('PROJECT') IS NOT NULL
DROP TABLE PROJECT;
GO


CREATE TABLE SDEV
(SDID NVARCHAR(50), 
DevName NVARCHAR(50), 
DEVADDRESS NVARCHAR(50),
PRIMARY KEY (SDID)
);

CREATE TABLE PROJECT
(ProjNum INT, 
TITLE NVARCHAR(50),
DESCRIPT NVARCHAR(50),
PRIMARY KEY (ProjNum),
);

CREATE TABLE WORKLOG
(SDID NVARCHAR(50), 
ProjNum INT, 
WeekNum INT, 
PRIMARY KEY (SDID, ProjNum, WeekNum), 
FOREIGN KEY (SDID) REFERENCES SDEV, 
FOREIGN KEY (ProjNum) REFERENCES PROJECT
);
GO

CREATE TABLE ALLOCATION
(SDID NVARCHAR(50), 
ProjNum INT,
WeekNum INT, 
PRIMARY KEY (SDID, ProjNum, WeekNum), 
FOREIGN KEY (SDID) REFERENCES SDEV,
FOREIGN KEY (ProjNum) REFERENCES PROJECT, 
FOREIGN KEY (WeekNum) REFERENCES WORKLOG 
);

GO

INSERT INTO SDEV (SDID, DevName, DEVADDRESS) VALUES
('SD101', 'Barry Manilow', '10 Wallaby Way'),
('SD201', 'Toni Bennet', '50th and Pine');

INSERT INTO PROJECT (ProjNum, TITLE, DESCRIPT) VALUES
('11', 'Nicuragua', 'Gold Oil and Drugs'),
('12', 'Russia', 'Radioactive Teacup');
