IF OBJECT_ID('CLUB') IS NOT NULL
DROP TABLE STAFF_ALLOCATION;
IF OBJECT_ID('STUDENT') IS NOT NULL
DROP TABLE ATTENDANCE;
IF OBJECT_ID('MEMBERSHIP') IS NOT NULL
DROP TABLE STUDENT;

GO

CREATE TABLE CLUB
(CName NVARCHAR(50), 
Descript NVARCHAR(50), 
PRIMARY KEY (CName)
);

CREATE TABLE STUDENT
(StudentID NVARCHAR(50), 
FullName NVARCHAR(50), 
PRIMARY KEY (StudentID)
);

CREATE TABLE MEMBERSHIP
(CName NVARCHAR(50), 
StudentID NVARCHAR(50), 
JoinDate DATETIME, 
LeaveDate DATETIME, 
PRIMARY KEY (CName, StudentID, JoinDate),
FOREIGN KEY (Cname) REFERENCES CLUB,
FOREIGN KEY (StudentID) REFERENCES STUDENT,
);
